#let raw_problems = (
  // Div.2 Number, Div.1 Number, Title, Difficulty, 예상 티어 "bsgpdr" 중 하나, 출제진 튜플 - 1명인 경우 뒤에 콤마 붙여야함
  // 정해 알고리즘, div2(AC, submission), div2 퍼솔, Div1(AC, submissions), Div1 퍼솔
    ("A", " ", "얼룩말을 찾아라!", "Beginner", "b", 
                (("이동훈", "aru0504"),), "implementation, string", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("B", "A", "이제는 더 이상 물러날 곳이 없다", "Easy", "b", 
                (("이동훈", "aru0504"),), "game_theory, ad_hoc", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("C", " ", "바닥수", "Easy", "b", 
                (("이동훈", "aru0504"), ("윤찬규", "dldyou")), "constructive, math", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("D", "B", "단체줄넘기", "Easy", "b", 
                (("이동훈", "aru0504"),), "implementation", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("E", " ", "팰린드롬 애너그램", "Normal", "s", 
                (("이동훈", "aru0504"),), "ad_hoc", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("F", "C", "현수막 걸기", "Normal", "s", 
                (("김수현", "creampuffshu"),), "binary_search", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("G", " ", "스위치", "Normal", "s", 
                (("윤찬규", "dldyou"),), "dynamic_programming", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("H", "D", "낚시", "Normal", "g", 
                (("이동훈", "aru0504"),), "prefix_sum", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("I", "E", "MEXchange", "Hard", "g", 
                (("김명기", "riroan"),), "ad_hoc, constructive", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    (" ", "F", "K-문자열", "Hard", "g", 
                (("김명기", "riroan"),), "string, bitmask, combinatorics", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    (" ", "G", "시간낭비", "Hard", "g", 
                (("이동훈", "aru0504"),), "dp, graphs, topological_sorting",
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    (" ", "H", "우정은 BFS처럼, 사랑은 DFS처럼", "Challenging", "p",
                (("이동훈", "aru0504"), ("윤찬규", "dldyou")), "constructive, greedy, graph_traversal", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    ("J", "I", "양손 정렬", "Challenging", "p",
                (("이동훈", "aru0504"), ("윤찬규", "dldyou"), ("김명기", "riroan")), "permutation_cycle_decomposition", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
    (" ", "J", "등불 날리기", "Challenging", "p", 
                (("윤찬규", "dldyou"),), "segment_tree, sliding_window", 
                (2, 5), ("이동훈", 5), (12, 30), ("김명기", 20)),
)

#let contest_problems = raw_problems.map( problem => {
  (
    d2: problem.at(0),
    d1: problem.at(1),
    title: problem.at(2),
    difftext: problem.at(3),
    diff: problem.at(4),
    setter: problem.at(5),
    algorithms: problem.at(6),
    d2_stat: problem.at(7),
    d2_first_ac: problem.at(8),
    d1_stat: problem.at(9),
    d1_first_ac: problem.at(10)
  )
})
